### PR TITLE
Display wowtoken.info  current NA stats

### PR DESCRIPTION
**Pull request by therealshibe**
I used your code to display the current wow token price on NA. 
You can try it out on my fork too. 
I thought you might want to integrate it. 
Sorry if it's not elegant, I'm extremely new to all this. 
Have a great day.

### CODE REVIEW

**Comment by ptoast** [comment]
Nice idea! I approve of this feature. However, I would like to modify `print_token` to do the text parsing without Pandoc, because I am in the process of removing the Pandoc requirement from the entire cog (see issue #2). I will keep this PR open while we refine it.

**Comment by therealshibe** [comment]
Sounds wonderful, Once I see how that's done I can try and tweak my part if needed.

**Comment by ptoast** [comment]
I've added a commit with my modifications.
* Support for specifying a region (NA is default if none specified)
* Only uses beatifulsoup4 and not Pandoc
* Added WoW token thumbnail picture

If you agree, I will merge this PR!

**Comment by therealshibe** [comment]
Awesome, I agree!

**Pull request merged**
