### PR TITLE
Send help if tts/gtts receive no text

### PR DESCRIPTION
**Pull request by skeith**
Added exception handling on tts/gtts

### CODE REVIEW

**Review by Quintenvw — APPROVED** [review]
This fixes the help but makes it so all tts letters are said one by one in stead of a word

**Comment by skeith** [comment]
It said as a word for me

**Comment by aikaterna** [comment]
Thanks for the contribution Yuki but v2 is dead and tts is in the v3 sfx cog, which is not on this repo.

**Comment by skeith** [comment]
> Thanks for the contribution Yuki but v2 is dead and tts is in the v3 sfx cog, which is not on this repo.

image

**Pull request closed without merging**
